import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { MEDIA_UPLOAD_CONTENT_TYPES } from './create-media-upload.dto';

export class MediaAssetResponseDto {
  @ApiProperty({ format: 'uuid' })
  id!: string;

  @ApiProperty({
    enum: ['profile_avatar', 'group_avatar', 'message_attachment'],
  })
  purpose!: 'profile_avatar' | 'group_avatar' | 'message_attachment';

  @ApiProperty({ enum: ['pending', 'ready', 'failed', 'deleted'] })
  status!: 'pending' | 'ready' | 'failed' | 'deleted';

  @ApiProperty({ enum: ['image', 'audio', 'video', 'document'] })
  type!: 'image' | 'audio' | 'video' | 'document';

  @ApiProperty({
    enum: MEDIA_UPLOAD_CONTENT_TYPES,
  })
  contentType!: string;

  @ApiProperty({ minimum: 1 })
  sizeBytes!: number;

  @ApiPropertyOptional({ type: String, nullable: true })
  originalFilename!: string | null;

  @ApiPropertyOptional({ type: Number, nullable: true, minimum: 1 })
  width!: number | null;

  @ApiPropertyOptional({ type: Number, nullable: true, minimum: 1 })
  height!: number | null;

  @ApiPropertyOptional({ type: Number, nullable: true, minimum: 1 })
  durationMs!: number | null;

  @ApiPropertyOptional({ type: String, nullable: true, format: 'uri' })
  secureUrl!: string | null;

  @ApiProperty({ format: 'date-time' })
  createdAt!: string;

  @ApiProperty({ format: 'date-time' })
  expiresAt!: string;

  @ApiPropertyOptional({ type: String, nullable: true, format: 'date-time' })
  completedAt!: string | null;
}

export class CloudinaryUploadFieldsDto {
  @ApiProperty({ description: 'Cloudinary API key; this is not a secret.' })
  api_key!: string;

  @ApiProperty()
  timestamp!: string;

  @ApiProperty({ description: 'Short-lived signature generated by the API.' })
  signature!: string;

  @ApiProperty({ description: 'Server-assigned immutable object identifier.' })
  public_id!: string;

  @ApiProperty({ description: 'Signed ownership and upload metadata.' })
  context!: string;

  @ApiProperty({ enum: ['upload'] })
  type!: 'upload';

  @ApiProperty({ enum: ['false'] })
  overwrite!: 'false';

  @ApiProperty({
    enum: [
      'jpg,jpeg,png,webp',
      'aac,m4a,mp3,ogg,wav',
      'mp4,mov,webm',
      'pdf,txt,docx,xlsx,pptx',
    ],
  })
  allowed_formats!:
    | 'jpg,jpeg,png,webp'
    | 'aac,m4a,mp3,ogg,wav'
    | 'mp4,mov,webm'
    | 'pdf,txt,docx,xlsx,pptx';

  @ApiProperty({
    description: 'Server-selected signed Cloudinary upload preset.',
  })
  upload_preset!: string;

  @ApiPropertyOptional({
    example: 'c_limit,h_2048,w_2048/q_auto',
    description:
      'Image-only signed incoming normalization that caps dimensions and strips private metadata from the stored original.',
  })
  transformation?: string;
}

export class CloudinaryUploadAuthorizationDto {
  @ApiProperty({ format: 'uri' })
  url!: string;

  @ApiProperty({ enum: ['POST'] })
  method!: 'POST';

  @ApiProperty({ format: 'date-time' })
  expiresAt!: string;

  @ApiProperty({ type: CloudinaryUploadFieldsDto })
  fields!: CloudinaryUploadFieldsDto;
}

export class CreateMediaUploadResponseDto {
  @ApiProperty({ type: MediaAssetResponseDto })
  media!: MediaAssetResponseDto;

  @ApiPropertyOptional({
    type: CloudinaryUploadAuthorizationDto,
    nullable: true,
    description:
      'Null when this idempotency key already belongs to a completed asset.',
  })
  upload!: CloudinaryUploadAuthorizationDto | null;
}
